name: Build and test

on: push

jobs:
    build:
        runs-on: windows-latest

        env:
            AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
            AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
            AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Install Rust
              uses: dtolnay/rust-toolchain@stable
            - name: Build and test
              run: cargo test
            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: "trusted-signing-cli.exe"
                  path: "target/release"
